### ISSUE TITLE
Consider using extern "C"

### ISSUE THREAD

**Issue by tombsar** [Rupt/c-arithmetic-right-shift#1]
Without `extern "C"` a C++ compiler is free to perform function name-mangling, which might be undesirable. A common idiom is:

```
#ifdef __cplusplus
extern "C" {
#endif
```

to cover the entire file, to save adding it to each declaration separately.

**Comment by Rupt** [comment]
Thank you for the suggestion.
In C, this would be clutter with no operation.
In C++, a user can simply wrap extern "C" around their #include if they wish to avoid name-mangling.
Do you think that should perhaps be added to the README?

**Comment by tombsar** [comment]
I understand the desire not to pollute your C code. ;)
I'd suggest adding it to the README code example.

**Comment by Rupt** [comment]
Added to README. Thank you.
