### ISSUE TITLE
Consider declaring functions as static and/or inline

### ISSUE THREAD

**Issue by tombsar** [Rupt/c-arithmetic-right-shift#2]
I suggest declaring all functions with `static inline` to prevent them from being exported (useful if the file is included multiple times in a program), and to avoid function-call overheads. This would seem to fit with the intended model of `#include`-ing the source file rather than compiling as a separate object file and linking.

**Comment by Rupt** [comment]
> useful if the file is included multiple times in a program

Thank you for highlighting this problem. I will add a `#define SAR_C` to help users put external include guards.

> I suggest declaring all functions with `static inline`

As far as I am aware, `inline` means nothing to modern compilers. It also doesn't exist in C89.

Static is interesting, I can imagine both static and non-static use cases. Do you know of a nice solution for both?

**Comment by tombsar** [comment]
> I will add a #define SAR_C to help users put external include guards.

That this will only help if the file is included multiple times in the same translation unit. The issue I am highlighting will exist (in theory; not tested) if the file is included by two separate source files that are then linked together.

> As far as I am aware, inline means nothing to modern compilers.

Note that it has different semantics in C and C++. I believe it does still have an effect for C.

> Do you know of a nice solution for both?

Not off the top of my head...

**Comment by Rupt** [comment]
@tombsar thanks to your suggestion I have learned a bit about static and decided to use it for the sar* functions.
A user could always define a thin non-static wrapper if desired but not the other way around.

**Comment by Rupt** [comment]
Decided you are right on inline.
